<?php

namespace Database\Seeders;

use App\Models\ClientMessageType;
use Illuminate\Database\Seeder;

class ClientMessageTypeSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->types() as $type) {
            ClientMessageType::firstOrCreate(
                ['name' => $type['name']],
                $type
            );
        }
    }

    private function types(): array
    {
        return [
            [
                'name' => 'Clarifications Message',
                'icon' => 'client-message-types/icons/1782646400_6a410680be471.png',
                'short_description' => 'Use this message type at the beginning of a project or a new phase when specific information, decisions, or confirmations are required from the client before work can continue.',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound! Thank you so much for your project.</p><p>To begin this project/phase smoothly, I need a few clarifications regarding the following points:</p><p>• [Clarification 1]<br>• [Clarification 2]<br>• [Clarification 3]</p><p>If it is easier, we can also arrange a Zoom meeting to discuss these points. We are available from 8:00 a.m. to 5:00 p.m. (GMT +6). Please let me know a suitable time for you.</p><p>Once I receive your clarification or confirmation, I will proceed with the project as quickly as possible.</p><p>Thank you for your time and cooperation. I look forward to your response.</p><p>Best Regards,</p>
HTML,
                'restriction' => <<<'HTML'
<p>Write a professional clarification message intended for the beginning of a project or a new project phase.</p><p>The message MUST NOT ask the client to communicate outside Fiverr (WhatsApp, Telegram, Discord, Skype, Email, Phone Number, etc.).</p><p>Never ask the client for passwords, OTPs, recovery codes, API secrets, private keys, or other sensitive credentials. If access is required, politely request collaborator or authorized access instead.</p><p>Only ask about the specific requirements that are unclear. Never ask the client to explain the entire project again or provide a complete project brief, as this may create the impression that the project was accepted without understanding the requirements.</p><p>Do not ask questions that are already answered in the project description or previous conversations.</p><p>Avoid making assumptions about missing requirements. Ask for confirmation whenever something is unclear.</p><p>Do not overwhelm the client with too many questions. Group related clarifications together and keep the message concise.</p><p>Do not introduce new feature requests, pricing discussions, or unrelated topics.</p><p>Do not guarantee delivery dates or functionality before receiving the required clarification.</p><p>Maintain a professional, respectful, and friendly tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Create a clarification message using the following structure.</p><p>Begin with a warm and professional greeting.</p><p>Thank the client for choosing our service and express appreciation for the opportunity to work on the project.</p><p>Clearly explain that a few clarifications are required before starting the project or the current phase.</p><p>List every clarification in an organized manner using bullet points or numbered points.</p><p>If appropriate, offer a Zoom meeting and mention that meetings are available between 8:00 a.m. and 5:00 p.m. (GMT +6).</p><p>Explain that development will continue immediately after receiving the required clarification or confirmation.</p><p>Thank the client for their cooperation and willingness to help.</p><p>End the message with a professional closing such as "Best Regards."</p><p>If the client does not respond within a reasonable time, a professional follow-up message should be sent while remaining polite and respectful.</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Update Message',
                'icon' => 'client-message-types/icons/1782646619_6a41075b81628.png',
                'short_description' => 'Use this message type to provide the client with a professional progress update after completing a milestone, task, or project phase',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>As per your order requirements and our previous discussion, I've completed the following tasks:</p><p>- I designed [UI/UX Task]<br>- I developed [Frontend Task]<br>- I developed [Backend/API Task]<br>- I optimized [Performance/SEO/Security/Database/etc.]</p><p>For your review, I have uploaded the latest version to my development/testing server.</p><p>Live Preview:<br>[Website_URL]</p><p>To help you better understand the completed work, I have also recorded an explanatory video.</p><p>Video Demonstration:<br>[Video_Link]</p><p>Please review everything at your convenience.</p><p>If you have any questions, feedback, or requested modifications, please let me know. I'll be happy to assist you and make the necessary adjustments.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the update message using only this structure. Do not change the order of the sections or create a different format.</p><p>Only mention work that has actually been completed. Never mention unfinished, planned, or estimated work as completed.</p><p>Use "designed" only when referring to UI/UX design work.</p><p>Use "developed" only when referring to Frontend, Backend, APIs, Database, or application functionality.</p><p>Use "optimized" only when referring to performance improvements, bug fixes, SEO, security, responsiveness, code refactoring, or similar enhancements.</p><p>If a live preview is available, clearly mention that it has been uploaded to the developer's development/testing server for the client's review. Never imply that it has already been deployed to the client's production server unless explicitly instructed.</p><p>Never include internal technical discussions, source code, credentials, server login details, or confidential project information.</p><p>Do not ask for project requirements, introduce new features, discuss pricing, or mention unrelated topics.</p><p>Maintain a professional, friendly, and confident tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>Thank or acknowledge the client's project before providing the update.</p><p>Clearly list every completed task using bullet points.</p><p>Use the correct terminology:<br>- "Designed" for UI/UX work.<br>- "Developed" for Frontend development.<br>- "Developed" for Backend development.<br>- "Optimized" for performance improvements, bug fixes, security, SEO, or similar work.</p><p>Always include the live preview link whenever one is available.</p><p>Always mention that the latest version has been uploaded to the developer's development/testing server for review.</p><p>Always include an explanatory video link demonstrating the completed work.</p><p>Invite the client to review the work and provide feedback or modification requests.</p><p>End the message with a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Fixing Message',
                'icon' => 'client-message-types/icons/1782646711_6a4107b7aef74.png',
                'short_description' => 'Use this message type when responding to client feedback, revisions, bug reports, or requested modifications. It informs the client that the requested changes have been completed and are ready for review.',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>Based on your last message/request, I have completed the following changes:</p><p>- I fixed [Issue/Fix 1]<br>- I updated [Issue/Fix 2]<br>- I optimized [Issue/Fix 3]</p><p>For your review, I have uploaded the latest version to my development/testing server.</p><p>Live Preview:<br>[Website_URL]</p><p>To help you better understand the completed changes, I have also recorded an explanatory video.</p><p>Video Demonstration:<br>[Video_Link]</p><p>Please review the updated version at your convenience.</p><p>If you notice anything else or would like additional modifications, please let me know. I'll be happy to assist you.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the fixing message using only this structure. Do not modify the order of the sections or create a different format.</p><p>Always refer to the client's previous message or requested modifications. Never present the fixes as unrelated updates.</p><p>Only mention issues that have actually been fixed or completed. Never state that a bug or request has been resolved unless it has been verified.</p><p>Use "fixed" for bugs, errors, broken functionality, or reported issues.</p><p>Use "updated" for requested changes, revisions, UI adjustments, content changes, or improvements.</p><p>Use "optimized" only for performance, security, responsiveness, SEO, code improvements, or similar enhancements.</p><p>If a live preview is available, clearly mention that it has been uploaded to the developer's development/testing server for review. Never imply that it has been deployed to the client's production server unless explicitly instructed.</p><p>Never include technical debugging details, internal discussions, source code, credentials, or confidential information.</p><p>Do not introduce new features, pricing discussions, or unrelated project updates.</p><p>Maintain a professional, friendly, and confident tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>Reference the client's previous message or requested modifications before listing the completed fixes.</p><p>Clearly list every completed fix using bullet points.</p><p>Use the correct terminology:<br>- "Fixed" for bugs, errors, or reported issues.<br>- "Updated" for requested revisions or modifications.<br>- "Optimized" for performance, security, SEO, responsiveness, or similar improvements.</p><p>Always include the live preview link whenever one is available.</p><p>Always mention that the latest version has been uploaded to the developer's development/testing server for review.</p><p>Always include an explanatory video link demonstrating the completed fixes.</p><p>Invite the client to review the updated version and share any additional feedback.</p><p>End the message with a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Delivery Message',
                'icon' => 'client-message-types/icons/1782646941_6a41089d23127.png',
                'short_description' => 'Use this message type when delivering a completed milestone or the entire project. It summarizes the completed work, provides all required deliverables, and requests the client to review and accept the delivery.',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>As per your order requirements and our previous discussions, I have successfully completed this project/phase.</p><p>Completed Work:</p><p>- I designed [UI/UX Task]<br>- I developed [Frontend Task]<br>- I developed [Backend/API Task]<br>- I optimized [Performance/Security/SEO/etc.]</p><p>For your review, I have uploaded the latest version to my development/testing server.</p><p>Website / Live Preview:<br>[Website_URL]</p><p>Admin Dashboard:<br>[Admin_URL]</p><p>Login Credentials:<br>[Credentials]</p><p>To help you better understand the completed work, I have also recorded a complete walkthrough video.</p><p>Video Demonstration:<br>[Video_Link]</p><p>Project Source Code:<br>[Google_Drive_Link]</p><p>Project Attachments:<br>[Attachment]</p><p>I've thoroughly tested the project, and everything is functioning properly based on the agreed scope.</p><p>Please take some time to review the website/application and let me know if you have any questions, feedback, or requested modifications.</p><p>As agreed in the order, I will continue providing support after delivery according to the agreed support period.</p><p>If everything looks good, I would greatly appreciate it if you could mark the order as complete.</p><p>Thank you for giving me the opportunity to work on your project. It has been a pleasure collaborating with you.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the delivery message using only this structure. Do not modify the order of the sections or create a different format.</p><p>Only mention work that was agreed upon in the original order requirements, project scope, or approved discussions. Never claim additional work that was not completed.</p><p>Do not include tasks that belong to future phases or upcoming milestones.</p><p>Use "designed" only for UI/UX work.</p><p>Use "developed" only for Frontend, Backend, APIs, Database, or application functionality.</p><p>Use "optimized" only for performance, SEO, security, responsiveness, bug fixes, or code improvements.</p><p>Always mention that the preview has been uploaded to the developer's development/testing server unless the project has been deployed to the client's production environment.</p><p>Never include confidential information, internal discussions, source code snippets, API keys, passwords, or sensitive credentials directly inside the message. If login details are required, provide them securely through the agreed delivery method.</p><p>Do not discuss pricing, additional features, or unrelated services within the delivery message.</p><p>Maintain a professional, confident, and appreciative tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>State that the project or current phase has been completed according to the agreed requirements and discussions.</p><p>List every completed deliverable using bullet points.</p><p>Only include tasks that were agreed upon for this delivery or project phase.</p><p>Use the correct terminology:<br>- "Designed" for UI/UX work.<br>- "Developed" for Frontend development.<br>- "Developed" for Backend development.<br>- "Optimized" for performance improvements, security, SEO, responsiveness, or similar enhancements.</p><p>Always provide the Website/Live Preview link whenever available.</p><p>Always provide the Admin Dashboard link whenever applicable.</p><p>Always provide the required login information or reference where the credentials can be found, following the agreed secure delivery method.</p><p>Always include an explanatory video demonstrating the completed project.</p><p>Always provide the complete source code using a Google Drive or other agreed download link.</p><p>Always include any required project attachments or documentation.</p><p>State that the project has been thoroughly tested before delivery.</p><p>Inform the client that post-delivery support will be provided according to the support period agreed in the order.</p><p>Invite the client to review the project and share any questions or modification requests.</p><p>Politely request the client to complete or accept the order if they are satisfied.</p><p>End the message with a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Credentials Request Message',
                'icon' => 'client-message-types/icons/1782647038_6a4108feb60ba.png',
                'short_description' => 'Use this message type when project access is required before development, deployment, or configuration can continue. Request only the credentials or access necessary for the current phase of the project.',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>To proceed smoothly with the project, I'll need the following access/credentials from your end:</p><p>1. Domain<br>2. Hosting Account (Hostinger, Namecheap, etc.)<br>3. Apple Developer Console<br>4. Google Developer Console<br>5. Firebase Account<br>6. [Any Additional Access Required]</p><p>If any additional access is required during the project, I'll let you know in advance.</p><p>If you need any assistance finding or sharing these credentials securely, I'd be happy to help.</p><p>If it's easier, we can also arrange a Zoom meeting to guide you through the process. We are available from 8:00 a.m. to 5:00 p.m. (GMT +6). Please let me know a suitable time for you.</p><p>Please let me know if you have any questions or concerns.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the credentials request using only this structure. Do not change the order of the sections or create a different format.</p><p>Only request credentials or account access that are required for the current project phase.</p><p>Never ask for unnecessary credentials or permissions that are unrelated to the project.</p><p>Whenever possible, request collaborator, team member, or delegated access instead of full account ownership.</p><p>Never request payment information, personal identification documents, recovery codes, two-factor authentication (2FA) codes, security questions, or any other sensitive personal information.</p><p>Do not ask the client to communicate or share credentials outside Fiverr.</p><p>Do not request credentials that have already been provided earlier in the conversation.</p><p>Keep the message professional, concise, and focused only on the required access.</p><p>Maintain a polite, respectful, and helpful tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>Clearly explain that the requested credentials or access are required to continue the current project phase.</p><p>List every required credential or account using a numbered list.</p><p>Only request access that is necessary for the agreed project scope.</p><p>Offer assistance if the client needs help locating or providing the required credentials.</p><p>Always offer a Zoom meeting if the client would like guidance sharing the required access.</p><p>Mention that Zoom meetings are available between 8:00 a.m. and 5:00 p.m. (GMT +6).</p><p>Invite the client to ask questions if anything is unclear.</p><p>If the client does not respond within a reasonable timeframe, send a polite follow-up requesting the pending credentials.</p><p>End the message with a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Follow-up Message',
                'icon' => 'client-message-types/icons/1782647148_6a41096cea882.png',
                'short_description' => 'Use this message type to politely remind the client about any pending action, such as a scheduled meeting, required credentials, clarification, feedback, approval, files, or any other information needed to continue the project.',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>I'm just following up regarding [Meeting / Credentials / Clarification / Feedback / Approval / Files / Pending Request].</p><p>As discussed in our previous conversation, I'm currently waiting for:</p><p>• [Pending Item 1]<br>• [Pending Item 2]</p><p>If this is regarding our scheduled meeting, I will be available at the agreed time and look forward to speaking with you.</p><p>If it's more convenient, we can also arrange another meeting between 8:00 a.m. and 5:00 p.m. (GMT +6). Please let me know a suitable time.</p><p>Once I receive the required information or confirmation, I'll continue working on the project immediately.</p><p>Please let me know if you have any questions or need any assistance.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the follow-up message using only this structure. Do not change the order of the sections or create a different format.</p><p>The follow-up must always be polite, professional, and respectful. Never sound demanding, impatient, or aggressive.</p><p>Only remind the client about pending items that were previously discussed or requested.</p><p>Never ask for new information unrelated to the original discussion.</p><p>Do not repeatedly send multiple reminders within a short period.</p><p>Do not blame or pressure the client for delayed responses.</p><p>Never discuss pricing, additional services, or unrelated project matters in a follow-up message.</p><p>If the follow-up is for a meeting, mention only the agreed meeting details.</p><p>Maintain a friendly and supportive tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>Clearly mention that the message is a follow-up regarding a previous discussion or request.</p><p>Specify exactly what information, approval, meeting, credentials, files, or feedback is still pending.</p><p>If the follow-up is related to a meeting, mention the scheduled meeting time or offer a meeting between 8:00 a.m. and 5:00 p.m. (GMT +6).</p><p>Explain that work will continue immediately after receiving the required response.</p><p>Offer assistance if the client needs help providing the requested information.</p><p>Invite the client to ask questions if anything is unclear.</p><p>End the message with a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Meeting Summary',
                'icon' => 'client-message-types/icons/1782647330_6a410a22979cc.png',
                'short_description' => 'Use this message type immediately after a meeting to summarize the discussion, document the agreed decisions, outline the next steps, and ensure both parties have a clear understanding of what was discussed.',
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>Thank you very much for taking the time to meet today. It was truly a productive and insightful discussion about "[Primary Meeting Topic]". I appreciate the opportunity to discuss your project and better understand your requirements.</p><p>Below is a summary of the key points we discussed during the meeting:</p><p>The following items were discussed:</p><p>- [Discussion Point 1]<br>- [Discussion Point 2]<br>- [Discussion Point 3]</p><p>Based on our discussion, I will proceed with the following agreed tasks:</p><p>- I will [Agreed Task 1]<br>- I will [Agreed Task 2]<br>- I will [Agreed Task 3]</p><p>[Optional]<br>Based on our discussion, I estimate that completing these tasks will take approximately [Estimated Time]. I will keep you updated on the progress throughout the development process.<br>[/Optional]</p><p>If I need any additional clarification during development, I will reach out to you.</p><p>If you have any questions or additional thoughts, please don't hesitate to let me know.</p><p>Thank you once again for your valuable time.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the meeting summary using only this structure. Do not change the order of the sections or create a different format.</p><p>Only summarize topics that were actually discussed during the meeting. Never add assumptions, opinions, or information that was not mentioned.</p><p>Only include action items that were mutually agreed upon during the meeting.</p><p>Do not promise features, timelines, deliverables, or functionality that were not confirmed during the meeting.</p><p>Include the estimated completion time only if it was discussed or agreed upon during the meeting. Otherwise, omit that section completely.</p><p>Do not mention emails, external documents, recordings, transcripts, or conversations outside Fiverr unless the client specifically referenced them during the meeting.</p><p>Do not ask the client to accept the delivery, leave a review, provide a rating, or share personal information.</p><p>Do not discuss pricing, invoices, additional services, or unrelated project topics unless they were part of the meeting discussion.</p><p>Maintain a professional, respectful, and objective tone throughout the summary.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>Thank the client for attending the meeting.</p><p>Mention the primary meeting topic inside quotation marks.</p><p>Provide a clear summary of all major discussion points using bullet points.</p><p>Clearly list the tasks that were mutually agreed upon during the meeting.</p><p>If an estimated completion time was discussed and agreed upon, include it. Otherwise, omit the estimation section.</p><p>Mention that you will reach out if additional clarification is required during development.</p><p>Invite the client to share any additional questions or thoughts.</p><p>End the message with appreciation and a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Work Progress Explanation',
                'icon' => 'client-message-types/icons/1782647424_6a410a80161b7.png',
                'short_description' => "Use this message type when a client requests clarification about the development workflow, project progress, delivery process, or current phase. It explains the project's development stages and sets clear expectations.",
                'format' => <<<'HTML'
<p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>Thank you for your message. I'd like to clarify our development workflow and explain how we are progressing with your project.</p><p>Our development process consists of the following phases:</p><p>1. UI/UX Design Phase</p><p>During this stage, we create the visual design and prototype of your project. This allows you to review the layout, colors, typography, branding, user experience, and overall structure. Your feedback is collected during this phase, and revisions are made before moving forward.</p><p>2. Frontend Development Phase</p><p>After the UI/UX design is approved, we begin developing the user interface based on the approved design. During this phase, we provide a preview or development version so you can review the implementation before backend functionality is integrated.</p><p>3. Backend Development Phase</p><p>Once the frontend is approved, we develop all backend functionality, APIs, database integration, business logic, and dynamic features. At the end of this phase, the project becomes fully functional according to the agreed requirements.</p><p>4. Testing &amp; Delivery Phase</p><p>Before delivery, we thoroughly test the project, fix any remaining issues, optimize performance, and prepare the final deliverables, including the source code, documentation, and any agreed project files.</p><p>5. Deployment Phase (Optional)</p><p>If deployment is included in our agreement, we will assist with deploying the project to the production server, App Store, Google Play, or other agreed platforms. Otherwise, deployment will be handled by the client.</p><p>Thank you for your understanding. If you have any questions regarding any phase of the project, please let me know. I'll be happy to explain further.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the work progress explanation using only this structure. Do not change the order of the sections or create a different format.</p><p>Only describe the project phases that are relevant to the current project. Omit any phase that does not apply.</p><p>Never promise delivery dates, timelines, or completion estimates unless they have already been agreed upon with the client.</p><p>Do not mention internal company processes, staff assignments, development tools, or confidential information.</p><p>Do not apologize unless there was an actual mistake or misunderstanding.</p><p>Do not discuss pricing, additional services, or unrelated project topics.</p><p>Do not ask the client to accept the delivery, leave a review, provide a rating, or share personal information.</p><p>Maintain a professional, reassuring, and informative tone throughout the message.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Start the message with a professional greeting.</p><p>Explain the purpose of the message and clarify the current development workflow.</p><p>Clearly describe each applicable project phase in chronological order.</p><p>Explain what will be completed during each phase and what the client can expect before moving to the next phase.</p><p>Only include phases that are part of the agreed project scope.</p><p>If deployment is included in the agreement, explain the deployment phase. Otherwise, clearly state that deployment is outside the agreed scope.</p><p>Invite the client to ask questions if any part of the process requires additional clarification.</p><p>End the message with appreciation and a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
            [
                'name' => 'Reply Message',
                'icon' => 'client-message-types/icons/1782647599_6a410b2f528fe.png',
                'short_description' => "Use this message type when responding to a client's message, question, request, feedback, or concern. The reply should acknowledge the client's message, address every point clearly, and maintain a professional and friendly conversation.",
                'format' => <<<'HTML'
<p>If replying immediately after receiving the client's message:</p><p>Hello [Client_Name],</p><p>Thank you for your message regarding [Topic/Request].</p><p>[Respond clearly to every question, request, or concern raised by the client.]</p><p>[Explain what action will be taken or answer the client's question.]</p><p>If you have anything else you'd like to discuss, please don't hesitate to let me know.</p><p>If needed, we can also arrange a Zoom meeting between 8:00 a.m. and 5:00 p.m. (GMT +6). Please let me know a suitable time.</p><p>Best Regards.</p><p><br>------------------------------------------------------------</p><p>If replying after some time has passed:</p><p>Hello [Client_Name],</p><p>I hope you and your family are safe and sound!</p><p>I have reviewed your previous message regarding [Topic/Request].</p><p>[Respond clearly to every question, request, or concern raised by the client.]</p><p>[Explain what action will be taken or answer the client's question.]</p><p>If you have anything else you'd like to discuss, please don't hesitate to let me know.</p><p>If needed, we can also arrange a Zoom meeting between 8:00 a.m. and 5:00 p.m. (GMT +6). Please let me know a suitable time.</p><p>Best Regards.</p>
HTML,
                'restriction' => <<<'HTML'
<p>Generate the reply using only this structure. Do not change the order of the sections or create a different format.</p><p>If replying immediately after the client's message, begin by thanking the client for their message or request.</p><p>If replying after a noticeable delay, begin with a professional greeting before acknowledging the client's previous message.</p><p>Always respond to every question, request, concern, or feedback provided by the client. Do not ignore any point.</p><p>Do not make promises, delivery estimates, or commitments unless they have been confirmed.</p><p>Do not discuss unrelated topics, pricing changes, or additional services unless the client asks.</p><p>Do not ask for reviews, ratings, order acceptance, or personal information.</p><p>Do not ask the client to communicate outside Fiverr.</p><p>Keep the reply concise, professional, friendly, and solution-oriented.</p>
HTML,
                'mandatory' => <<<'HTML'
<p>Determine whether the reply is immediate or delayed and use the appropriate opening.</p><p>Acknowledge the client's message, request, question, or feedback.</p><p>Respond to every point raised by the client with a clear and complete answer.</p><p>Explain any action that will be taken or any information the client requested.</p><p>If additional clarification is required, politely ask only the necessary questions.</p><p>If a meeting would help resolve the discussion, offer a Zoom meeting between 8:00 a.m. and 5:00 p.m. (GMT +6).</p><p>Invite the client to continue the conversation if they have additional questions or concerns.</p><p>End the message with a professional closing such as "Best Regards."</p>
HTML,
                'status' => 'active',
            ],
        ];
    }
}
